[package]
name = "chip8"
version = "0.1.0"
authors = ["pierreyoda <pierreyoda@users.noreply.github.com>"]

[[bin]]
name="rust-chip8"

[lib]
name = "chip8vm"
path = "src/lib.rs"

[dependencies]
time = "0.1.37"
log = "0.3.7"
getopts = "0.2.14"
rand = "0.3.15"
sdl2 = "0.30.0-beta"
