[package]
name = "chip8"
version = "0.1.0"
authors = ["pierreyoda <pierreyoda@users.noreply.github.com>"]

[[bin]]
name="rust-chip8"

[lib]
name = "chip8vm"
patch = "src/lib.rs"

[dependencies]
log = "0.3.1"
getopts = "0.2.10"
rand = "0.3.8"
sdl2 = "0.2.3"
